language: python
python:
  - 3.9
services:
  - docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin # Login to dockerhub

script:
  - docker build -t leersma/tamikabot:latest .

deploy:
  provider: script
  script:
    docker push leersma/tamikabot:latest;
  on:
    branch: main